export const CREATE_CLIENT = 'CREATE_CLIENT';
export const UPDATE_CLIENTS = 'UPDATE_CLIENTS';
export const SEARCH_CLIENT = 'SEARCH_CLIENT';
export const FETCH_ALL_CLIENTS = 'FETCH_ALL_CLIENTS';
export const FETCH_ALL_COMPANIES = 'FETCH_ALL_COMPANIES';
export const CREATE_COMPANY = 'CREATE_COMPANY';